config/routes.rb
Rails.application.routes.draw do
  resources :bolog_lists

  resources :todo_lists

end

app/models/bolog_list.rb
class BologList < ActiveRecord::Base
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bolog_lists_controller.rb
class BologListsController < ApplicationController
  before_action :set_bolog_list, only: [:show, :edit, :update, :destroy]

  # GET /bolog_lists
  # GET /bolog_lists.json
  def index
    @bolog_lists = BologList.all
  end

  # GET /bolog_lists/1
  # GET /bolog_lists/1.json
  def show
  end

  # GET /bolog_lists/new
  def new
    @bolog_list = BologList.new
  end

  # GET /bolog_lists/1/edit
  def edit
  end

  # POST /bolog_lists
  # POST /bolog_lists.json
  def create
    @bolog_list = BologList.new(bolog_list_params)

    respond_to do |format|
      if @bolog_list.save
        format.html { redirect_to @bolog_list, notice: 'Bolog list was successfully created.' }
        format.json { render :show, status: :created, location: @bolog_list }
      else
        format.html { render :new }
        format.json { render json: @bolog_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bolog_lists/1
  # PATCH/PUT /bolog_lists/1.json
  def update
    respond_to do |format|
      if @bolog_list.update(bolog_list_params)
        format.html { redirect_to @bolog_list, notice: 'Bolog list was successfully updated.' }
        format.json { render :show, status: :ok, location: @bolog_list }
      else
        format.html { render :edit }
        format.json { render json: @bolog_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bolog_lists/1
  # DELETE /bolog_lists/1.json
  def destroy
    @bolog_list.destroy
    respond_to do |format|
      format.html { redirect_to bolog_lists_url, notice: 'Bolog list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bolog_list
      @bolog_list = BologList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bolog_list_params
      params.require(:bolog_list).permit(:title, :description)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bolog_lists_helper.rb
module BologListsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/bolog_lists/_form.html.erb
<%= form_for(@bolog_list) do |f| %>
  <% if @bolog_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bolog_list.errors.count, "error") %> prohibited this bolog_list from being saved:</h2>

      <ul>
      <% @bolog_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bolog_lists/edit.html.erb
<h1>Editing bolog_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @bolog_list %> |
<%= link_to 'Back', bolog_lists_path %>

app/views/bolog_lists/index.html.erb
<h1>Listing bolog_lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bolog_lists.each do |bolog_list| %>
      <tr>
        <td><%= bolog_list.title %></td>
        <td><%= bolog_list.description %></td>
        <td><%= link_to 'Show', bolog_list %></td>
        <td><%= link_to 'Edit', edit_bolog_list_path(bolog_list) %></td>
        <td><%= link_to 'Destroy', bolog_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bolog list', new_bolog_list_path %>

app/views/bolog_lists/new.html.erb
<h1>New bolog_list</h1>

<%= render 'form' %>

<%= link_to 'Back', bolog_lists_path %>

app/views/bolog_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bolog_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bolog_list.description %>
</p>

<%= link_to 'Edit', edit_bolog_list_path(@bolog_list) %> |
<%= link_to 'Back', bolog_lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Odot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing todo_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<h1>Listing todo_lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.title %></td>
        <td><%= todo_list.description %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo list', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New todo_list</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>